/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "x_out_aliases.h"
#include "x_out.h"
#include "x_DAC.h"
#include "y_out_aliases.h"
#include "y_out.h"
#include "y_DAC.h"
#include "FPS_Clock.h"
#include "FPS_isr.h"
#include "BLE_UART.h"
#include "BLE_Rx_isr.h"
#include "LCD.h"
#include "Audio_isr.h"
#include "Audio_out_aliases.h"
#include "Audio_out.h"
#include "Audio_Clock.h"
#include "SD_FS.h"
#include "Audio_DAC.h"
#include "BLE_UART_IntClock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "SD_FS_SPI0.h"
#include "SD_FS_SPI0_PVT.h"
#include "SD_FS_mosi0_aliases.h"
#include "SD_FS_mosi0.h"
#include "SD_FS_Clock_1.h"
#include "SD_FS_miso0_aliases.h"
#include "SD_FS_miso0.h"
#include "SD_FS_sclk0_aliases.h"
#include "SD_FS_sclk0.h"
#include "SD_FS_SPI0_CS_aliases.h"
#include "SD_FS_SPI0_CS.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

